---
paths:
  models_dir: '/path/to/models/'
  plot_data: '/path/to/plot_data/'
 
games: ['connect_four', 'pentago', 'oware', 'checkers']

game_paths:
  connect_four: 'connect_four_10000/'
  pentago: 'pentago_t5_10000/'
  oware: 'oware_10000/'
  checkers: 'checkers/'

action_formats:
  connect_four: '[xo][0-6]'
  pentago: '[a-f][1-6][s-z]'
  oware: '[A-F,a-f]'
  checkers: '[a-h][1-8][a-h][1-8]'

approx_training_length:
    connect_four: 70_000
    pentago: 50_000
    oware: 10_000
    checkers: 10_000